// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 11 Jan 2018 10:06:18 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "nanovg.h"
#include "nanovg_gl_cgo.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

