// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 11 Jan 2018 11:32:52 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package nvg provides Go bindings for nanovg.
*/
package nvg
